data:
  gpu: 0
  num_workers: 3
  in_dataset: ./tmp/cifar_in.beton
  val_dataset: ./tmp/cifar_test.beton
  out_dataset: ./tmp/cifar_out.beton
  out_dataset_index: ./tmp/out.npy
  in_dataset_index: ./tmp/in.npy
  model_folder: ./models

training:
  batch_size: 512
  epochs: 24
  lr: 0.5
  momentum: 0.9
  lr_peak_epoch: 5
  momentum: 0.9
  weight_decay: 5e-4
  label_smoothing: 0.1
  lr_tta: true
  num_workers: 3
  in_model_save_path: ./models/model_in.pth
