data:
  gpu: 0
  num_workers: 3
  model_folder: /users/home/ygu27/cifar/models/ #your absolute addr to store the experiment models, not shadow models
  attacking_results_folder: ./data/results/
  dataset_folder: /users/home/ygu27/cifar/tmp/ #your absolute addr to store the in, out dataset and index files
  statistic_in: ./data/static/in_statistics.csv
  statistic_out: ./data/static/out_statistics.csv

training:
  batch_size: 512
